### PR TITLE
Add option Judge max trials per game

### PR DESCRIPTION
**Pull request by hinhinarrrrrr**

### CODE REVIEW

**Comment by hinhinarrrrrr** [comment]
wait

**Comment by Tommy-XL** [comment]
Can you write me your nickname so that I can write in the 2.1.0 changes?
Idk what your Discord account is and obviously your github name isn't really yours lol

**Comment by KingPanda360** [comment]
> Can you write me your nickname for write in the 2.1.0 changes? Idk what your Discord account is and obviously your github name isn't really yours lol

I think their discord account is the same as their github name because I found a person named "hinhinarrrrrr" on the TOHE Discord.

**Comment by hinhinarrrrrr** [comment]
> Can you write me your nickname for write in the 2.1.0 changes? Idk what your Discord account is and obviously your github name isn't really yours lol

 just call me "hin" discord name:Hinhinarrrrrr

**Pull request merged**
