### PR TITLE
Development v2.1.0

### PR DESCRIPTION
**Pull request by Tommy-XL**
- [x] Neutral Apocalypse #815 
- [x] TextBoxPatch #934
- [x] Disable ShapeShift Menu for Reject Shapeshift roles #959
- [x] "Shield Person Died First" Rework #1038
- [x] Cancel Vote System #918 
- [x] AddonBase + Spurt #1145
- [x] Some UI Adittions and search bar #1115 
- [x] Better RegionMenu #1150 
- [x] New role: New Role: Troller #1148
- [x] Desync Shapeshifter #951
- [x] New Role: Double Agent #1125 
- [x] New Ghost Role: Possessor  #1162 
- [x] New Role: YinYanger #1167 
- [x] New Add-on: Evader #1184 
- [x] Role Basis Changer & Reviving dead players (Port from TOH-Y) #1182
- [x] Better AntiBlackout #1188
- [x] Fix Phantom For Desync Roles #1189 
- [x] Disable Use Vent For Vanilla (Port from MoreGamemodes) #1186
- [x] New Add-on: Sloth #1199
- [x] New Add-on: Prohibited #1210
- [x] New role: Ventguard #1219

### CODE REVIEW

**Comment by Ultradragon005** [comment]
time to finally merge all those PR's 😂

**Comment by MargaretTheFool** [comment]
> time to finally merge all those PR's 😂

GAPgOlsWMAAXv-V

**Comment by D1GQ** [comment]
> time to finally merge all those PR's 😂

PR's be like
https://images.app.goo.gl/PNQrHLcKWbkSLraj6

**Comment by Ultradragon005** [comment]
> PR's be like https://tenor.com/bGZaq.gif

image

**Comment by D1GQ** [comment]
> > PR's be like https://tenor.com/bGZaq.gif
> 
> image [ image ](https://camo.githubusercontent.com/0a6f35cabb2d8d96b06fb0bc867c123abc8125bdab140abc22a1e1a2ef772ab9/68747470733a2f2f632e74656e6f722e636f6d2f654c45753954573032315541414141642f74656e6f722e676966) [ ](https://camo.githubusercontent.com/0a6f35cabb2d8d96b06fb0bc867c123abc8125bdab140abc22a1e1a2ef772ab9/68747470733a2f2f632e74656e6f722e636f6d2f654c45753954573032315541414141642f74656e6f722e676966)

programmerhumor-io-programming-memes-e9a205be81be140

**Comment by D1GQ** [comment]
I think there are going to be Conflicts with Cancel Vote System and Double Agent!

**Comment by Ultradragon005** [comment]
dople agent. I mean jsut include it. ther conflicts aren't big

**Comment by D1GQ** [comment]
> dople agent. I mean jsut include it. ther conflicts aren't big

Dople Agent?

**Comment by Ultradragon005** [comment]
> Dople Agent?

POTWOJNY AGENT!!!!

**Comment by Dxgamer7405** [comment]
DAYUMMM

**Pull request merged**
