### PR TITLE
New RPC detection

### PR DESCRIPTION
**Pull request by Luckyheat**
KillNetwork Detection {250} [KN-Chat already removed from KillNetwork]

### CODE REVIEW

**Comment by NikoCat233** [comment]
bruh
btw kill network 250 is already included in our dev branch

**Comment by Luckyheat** [comment]
> bruh btw kill network 250 is already included in our dev branch

Then don't spam on dm's to add this, lol

**Comment by redphantom1000** [comment]
i beat ya to it lol

**Comment by NikoCat233** [comment]
who would spam dms for this

**Comment by redphantom1000** [comment]
bruh

**Pull request closed without merging**
