### PR TITLE
Rework Jackal and Sidekick

### PR DESCRIPTION
**Pull request by hinhinarrrrrr**
As before,the vanilla cant change their role basis to impostor.Jackal need to assign  Recruited and Sidekick to divide the non-killbutton and have killbutton But now we can change their role basis.So we can compare them.Sidekick will inherit jackal role as TOR(The Other Roles).Sidekick cant kill before inherited(depend on setting).

Known Bug: When jackal recruit sidekick,if origin role of sidekick have task,the name will show task 
螢幕擷取畫面 2024-10-06 140844
I dont know how to fix it...

### CODE REVIEW

**Comment by hinhinarrrrrr** [comment]
should i delete the addon Recruit

**Comment by Tommy-XL** [comment]
I would say this is the best rework Sidekick option
https://discord.com/channels/1094344790910455908/1253116596591919175/1286958464068747295

**Comment by hinhinarrrrrr** [comment]
> I would say this is the best rework Sidekick option https://discord.com/channels/1094344790910455908/1253116596591919175/1286958464068747295
i will add 1 and 2.But wdym number 3.random player become jackal from other role when origin jackal dies In game,not assign before game start?

**Comment by Tommy-XL** [comment]
> random player become jackal from other role when origin jackal dies In game,not assign before game start?

I mean random player become new jackal that not have Sidekick (except Imps)

**Comment by NikoCat233** [comment]
WTF why you dont allow edits from maintainer

**Comment by NikoCat233** [comment]
I will code a better one i guess

**Comment by NikoCat233** [comment]
Replaced by #1292

**Pull request closed without merging**
