### PR TITLE
Unhide Team Guessing

### PR DESCRIPTION
**Pull request by MargaretTheFool**

### CODE REVIEW

**Comment by Tommy-XL** [comment]
Are these settings used in the code?

**Comment by MargaretTheFool** [comment]
i know apoc guess apoc is because I coded that myself, I think the other two are used because I probably looked at those to code apoc guess apoc

**Comment by Tommy-XL** [comment]
image

These settings are only used for modded players, but in the meantime the vanilla code does not check these settings, so they are simply partially unused

**Comment by MargaretTheFool** [comment]
ok NOW they are

**Pull request merged**
