### PR TITLE
100 player lobby (Ported from crowded)

### PR DESCRIPTION
**Pull request by ryuk201198**

### CODE REVIEW

**Comment by Pietrodjaowjao** [comment]
apparently github reverted the entire rolebase while trying to fix conflicts

**Comment by Pietrodjaowjao** [comment]
its extremely hard to do the other part but its partially done, i will finish tomorrow ig

**Comment by Tommy-XL** [comment]
Actually the Crowded code has some problems with null errors, so I'm not sure if it's worth merging

**Comment by NikoCat233** [comment]
I still dont think tohe should include crowded feature directly

**Comment by NikoCat233** [comment]
> Actually the Crowded code has some problems with null errors, so I'm not sure if it's worth merging

null is probably caused by reference to numberoptions in gameoptionsmenu, where tohe will build a tab without number options and crowded try to search for it

**Comment by Wannacry-ops** [comment]
from where the 100 players will be placed from where you create it or by commands and if so, what would it be?

**Comment by Ultradragon005** [comment]
ya'll, this is crazy

**Comment by NikoCat233** [comment]
should be replaced by this
https://github.com/NikoCat233/CrowdedMod/releases/tag/v0.0.1

**Comment by NikoCat233** [comment]
Unforetunely I added crowded in dev 2.2.0

**Pull request closed without merging**
