### PR TITLE
Fix being able to set more than 15 players in vanilla regions

### PR DESCRIPTION
**Pull request by Pietrodjaowjao**
This will cancel the command if the input is bigger than 15 and its in a vanilla region

### CODE REVIEW

**Comment by Pietrodjaowjao** [comment]
i have no idea why it added so many unecessary changes to chatcommandpatch.

**Comment by PEPPERcula** [comment]
> i have no idea why it added so many unecessary changes to chatcommandpatch.

Yeah I also had the same issue where I edit like 2 lines of code then it changes the whole file to the point it messes it up.

**Comment by NikoCat233** [comment]
https://github.com/EnhancedNetwork/TownofHost-Enhanced/blob/7f390dace0ed5dedecc32f85ada6f1d025c05924/Patches/GameOptionsMenuPatch.cs#L499

Mind look into this? lol

**Comment by NikoCat233** [comment]
Visual studio is ok btw

**Review by NikoCat233 — APPROVED** [review]

**Pull request merged**
